// Code generated by protoc-gen-go.
// source: data.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	FileMetadata
	DirEntry
	Dir
*/
package main

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FileMetadata struct {
	Length           *int64  `protobuf:"varint,1,opt,name=length" json:"length,omitempty"`
	Md5              []byte  `protobuf:"bytes,2,opt,name=md5" json:"md5,omitempty"`
	CreationTime     *uint64 `protobuf:"varint,3,opt,name=creation_time" json:"creation_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FileMetadata) Reset()         { *m = FileMetadata{} }
func (m *FileMetadata) String() string { return proto.CompactTextString(m) }
func (*FileMetadata) ProtoMessage()    {}

func (m *FileMetadata) GetLength() int64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *FileMetadata) GetMd5() []byte {
	if m != nil {
		return m.Md5
	}
	return nil
}

func (m *FileMetadata) GetCreationTime() uint64 {
	if m != nil && m.CreationTime != nil {
		return *m.CreationTime
	}
	return 0
}

type DirEntry struct {
	Name             *string       `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Type             *int32        `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	ChunkId          *string       `protobuf:"bytes,3,opt,name=chunk_id" json:"chunk_id,omitempty"`
	Metadata         *FileMetadata `protobuf:"bytes,4,opt,name=metadata" json:"metadata,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *DirEntry) Reset()         { *m = DirEntry{} }
func (m *DirEntry) String() string { return proto.CompactTextString(m) }
func (*DirEntry) ProtoMessage()    {}

func (m *DirEntry) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *DirEntry) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *DirEntry) GetChunkId() string {
	if m != nil && m.ChunkId != nil {
		return *m.ChunkId
	}
	return ""
}

func (m *DirEntry) GetMetadata() *FileMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Dir struct {
	Entries          []*DirEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Dir) Reset()         { *m = Dir{} }
func (m *Dir) String() string { return proto.CompactTextString(m) }
func (*Dir) ProtoMessage()    {}

func (m *Dir) GetEntries() []*DirEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
}
